version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "fix"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "fix"
      include: "scope"
