exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-xml
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
        exclude: "(^.idea/|.vscode/)"
      - id: trailing-whitespace
        exclude: "(^.idea/|.vscode/|docs/)"
      - id: end-of-file-fixer
        exclude: "(^.idea/|.vscode/|docs/)"

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          # automated security testing
          - flake8-bandit

          # do not allow breaking lines with backslashes
          - flake8-broken-line

          # check for built-ins being used as variables or parameters
          - flake8-builtins

          # "find likely bugs and design problems in your program"
          - flake8-bugbear

          # write better comprehensions
          - flake8-comprehensions

          # catch bugs from implicit concat
          - flake8-no-implicit-concat

          # attempt to simplify code
          - flake8-simplify

          # validate names of things
          - pep8-naming
