exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: "(^.idea/|^docs/)"
      - id: end-of-file-fixer
        exclude: "(^.idea/|^docs/)"

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations
          - flake8-bandit
          - flake8-black
          - flake8-broken-line
          - flake8-builtins
          - flake8-bugbear
          - flake8-commas
          - flake8-comprehensions
          - flake8-isort
          - flake8-no-implicit-concat
          - flake8-quotes
          - flake8-simplify
          - pep8-naming
