security:
  continue-on-vulnerability-error: False
  ignore-cvss-severity-below: 0
  ignore-cvss-unknown-severity: False
  ignore-vulnerabilities:
    70612:
      reason: "No new release has been made and the vulnerability is kind of bogus."
      expires: "2024-10-01"
