[tool.poetry]
name = "ghpypi"
version = "0.0.0"  # DO NOT CHANGE -- set during build
description = "A custom package index generator."
authors = ["Paul Lockaby <paul@paullockaby.com>"]
packages = [{include = "ghpypi", from = "src"}]

[tool.poetry.scripts]
ghpypi = "ghpypi:main"

[tool.poetry.dependencies]
python = "^3.8"
PyGithub = "^1.55"
distlib = "^0.3.4"
Jinja2 = "^3.1.2"
packaging = "^21.3"
atomicwrites = "^1.4.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.8.2"
pytest-mypy = "^0.9.1"
pytest-flake8 = "^1.1.1"
pytest-cov = "^3.0.0"
flake8-annotations = "^2.9.0"
flake8-bandit = "^3.0.0"
flake8-broken-line = "^0.4.0"
flake8-builtins = "^1.5.3"
flake8-bugbear = "^22.7.1"
flake8-commas = "^2.1.0"
flake8-comprehensions = "^3.10.0"
flake8-isort = "^4.1.1"
flake8-no-implicit-concat = "^0.3.3"
flake8-pylint = "^0.1.3"
flake8-quotes = "^3.3.1"
flake8-simplify = "^0.19.2"
pep8-naming = "^0.13.0"
types-requests = "^2.28.0"
types-atomicwrites = "^1.4.5"
responses = "^0.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
#addopts = "--flake8 --mypy --cov=src --cov-report=term --cov-report=html --log-level=ERROR -p no:warnings"
