name: Generate Index

on:
  # allow manual triggers
  workflow_dispatch:

  # allow programmatic triggers
  repository_dispatch:

  # run every monday at 12am, UTC
  schedule:
    - cron: "0 0 * * 1"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"

      - name: generate index
        run: |
          pip install poetry
          poetry install --no-ansi --no-interaction --without=dev
          poetry run ghpypi --output=docs --repositories=repositories.txt --token=${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: automatic index update [skip ci]
