name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: build
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.create true
          poetry install --no-ansi --no-interaction

      - name: test
        run: |
          poetry run pytest
